// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqEV-GvVGHDW1XBlaLNoutxUST1m9yGe8',
    appId: '1:680990892649:web:79934a87d03256e58438f8',
    messagingSenderId: '680990892649',
    projectId: 'ks-smart-test-fluttervinu',
    authDomain: 'ks-smart-test-fluttervinu.firebaseapp.com',
    storageBucket: 'ks-smart-test-fluttervinu.appspot.com',
    measurementId: 'G-08Q4SM9JQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgEbYw3As459RrAtNsFdEVyd9M4Cz-Wpc',
    appId: '1:680990892649:android:b10a188bde020ad78438f8',
    messagingSenderId: '680990892649',
    projectId: 'ks-smart-test-fluttervinu',
    storageBucket: 'ks-smart-test-fluttervinu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCChEX2g7y8JrVWxLCBNbPyXzZWStlB_w8',
    appId: '1:680990892649:ios:4995dc687919e23c8438f8',
    messagingSenderId: '680990892649',
    projectId: 'ks-smart-test-fluttervinu',
    storageBucket: 'ks-smart-test-fluttervinu.appspot.com',
    iosClientId: '680990892649-rc4b7j24bal52lvqlo1g4oejaentf3q2.apps.googleusercontent.com',
    iosBundleId: 'com.example.ksSmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCChEX2g7y8JrVWxLCBNbPyXzZWStlB_w8',
    appId: '1:680990892649:ios:4995dc687919e23c8438f8',
    messagingSenderId: '680990892649',
    projectId: 'ks-smart-test-fluttervinu',
    storageBucket: 'ks-smart-test-fluttervinu.appspot.com',
    iosClientId: '680990892649-rc4b7j24bal52lvqlo1g4oejaentf3q2.apps.googleusercontent.com',
    iosBundleId: 'com.example.ksSmart',
  );
}
