// File generated by FlutterFire CLI.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWtflGJmkJwxFm9QZnSVLB6xlCQ1qc-40',
    appId: '1:632753299966:web:4a44ed3c72cf1be50ea0af',
    messagingSenderId: '632753299966',
    projectId: 'ks-smart-machine-test',
    authDomain: 'ks-smart-machine-test.firebaseapp.com',
    storageBucket: 'ks-smart-machine-test.appspot.com',
    measurementId: 'G-4YNC2BQ2ND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA75el-GzKBwxO6yQQttTGMvkrGsQFEjWE',
    appId: '1:632753299966:android:736fc3ea8c534d7e0ea0af',
    messagingSenderId: '632753299966',
    projectId: 'ks-smart-machine-test',
    storageBucket: 'ks-smart-machine-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgwz6q5rYk4bfAVmiTZ5v6wkr6F3q1AAU',
    appId: '1:632753299966:ios:94dca5e5e2d8ceba0ea0af',
    messagingSenderId: '632753299966',
    projectId: 'ks-smart-machine-test',
    storageBucket: 'ks-smart-machine-test.appspot.com',
    androidClientId:
        '632753299966-qlnpgtcnfilh73aqek6lmahqb7mvd759.apps.googleusercontent.com',
    iosClientId:
        '632753299966-qg710gk9dmj8ch05hi44alo49gikbgdm.apps.googleusercontent.com',
    iosBundleId: 'com.example.ksSmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgwz6q5rYk4bfAVmiTZ5v6wkr6F3q1AAU',
    appId: '1:632753299966:ios:94dca5e5e2d8ceba0ea0af',
    messagingSenderId: '632753299966',
    projectId: 'ks-smart-machine-test',
    storageBucket: 'ks-smart-machine-test.appspot.com',
    androidClientId:
        '632753299966-qlnpgtcnfilh73aqek6lmahqb7mvd759.apps.googleusercontent.com',
    iosClientId:
        '632753299966-qg710gk9dmj8ch05hi44alo49gikbgdm.apps.googleusercontent.com',
    iosBundleId: 'com.example.ksSmart',
  );
}
